name: odelia
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pandas=2.0.3
  - numpy=1.24.3
  - tqdm=4.66.5
  - openpyxl=3.1.5
  - torchio=0.20.1
  - pytorch-cuda=11.8
  - pytorch=2.3.0
  - torchvision=0.18
  - torchmetrics=1.4
  - monai=1.3.2
  - pytorch-lightning=2.3.0
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.13.2
  - wandb=0.16.6
  - pillow=10.4.0
  - nibabel=5.2.1
