name: odelia
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - numpy
  - tqdm
  - openpyxl
  - torchio
  - pytorch-cuda=11.8
  - pytorch 
  - torchvision 
  - torchaudio 
  - monai
  - pytorch-lightning
  - scikit-learn
  - matplotlib
  - seaborn 
  - wandb
  - -e .